// RYDZ Admin - Riders Page

function renderRiders(){var tb=document.getElementById('r-tbody');var q=(document.getElementById('r-search').value||'').toLowerCase();var rl=users.filter(function(u){return u.role!=='driver'&&u.role!=='admin'});if(q)rl=rl.filter(function(u){return(u.name||'').toLowerCase().indexOf(q)>=0||(u.email||'').toLowerCase().indexOf(q)>=0||(u.phone||'').indexOf(q)>=0});
tb.innerHTML=rl.map(function(u){var ur=rides.filter(function(r){return r.rider_id===u.id});var c=ur.filter(function(r){return r.status==='completed'}).length;var x=ur.filter(function(r){return r.status==='cancelled'}).length;var joined=u.signup_date?new Date(u.signup_date).toLocaleDateString():(u.created_at?new Date(u.created_at).toLocaleDateString():'--');var st=u.disabled?'<span class="badge dis">Disabled</span>':'<span class="badge on">Active</span>';
return'<tr data-xid="'+u.id+'" onclick="openRdrPN(this.dataset.xid)"><td><strong>'+esc(u.name||'--')+'</strong></td><td style="color:var(--tx3)">'+esc(u.email||'-')+'</td><td>'+esc(u.phone||'-')+'</td><td style="color:var(--tx3);font-size:12px">'+joined+'</td><td>'+st+'</td></tr>'}).join('')}
async function openRdrPN(uid){var u=users.find(function(x){return x.id===uid});if(!u)return;var ur=rides.filter(function(r){return r.rider_id===uid});var c=ur.filter(function(r){return r.status==='completed'}).length;var x=ur.filter(function(r){return r.status==='cancelled'}).length;var joined=u.signup_date?new Date(u.signup_date).toLocaleDateString():(u.created_at?new Date(u.created_at).toLocaleDateString():'--');
var notes=await api('GET','admin_notes','?user_id=eq.'+encodeURIComponent(uid)+'&order=created_at.desc');
document.getElementById('pn-title').textContent=u.name||'Rider';
document.getElementById('pn-body').innerHTML=sect('Profile',row('Name',u.name)+row('Email',u.email)+row('Phone',u.phone)+row('Joined',joined)+row('Account',u.disabled?'<span class="badge dis">Disabled</span>':'<span class="badge on">Active</span>'))+sect('Ride Stats',row('Total Rides',ur.length)+row('Completed','<span style="color:var(--gn)">'+c+'</span>')+row('Cancelled','<span style="color:var(--rd)">'+x+'</span>')+row('Cancel Rate',(ur.length?Math.round(x/ur.length*100):0)+'%'))+sect('Notes',noteBlock(uid,notes))+sect('Recent Rides',ur.slice(0,8).map(function(r){var sc=r.status==='completed'?'var(--gn)':r.status==='cancelled'?'var(--rd)':'var(--bl)';return'<div class="pn-row"><span class="lb" style="font-size:11px">'+esc((r.pickup||'').substring(0,25))+'</span><span class="badge" style="background:'+sc+'22;color:'+sc+'">'+r.status+'</span></div>'}).join(''));
document.getElementById('pn-acts').innerHTML=u.disabled?'<button class="btn-p" data-xid="'+uid+'" onclick="togDis(this.dataset.xid,false)">Enable Account</button>':'<button class="btn-d" data-xid="'+uid+'" onclick="togDis(this.dataset.xid,true)">Disable Account</button>';
openPN()}
