// RYDZ Admin - Settings

async function loadSettings(){var r=await api('GET','settings','?id=eq.1');if(r&&r[0]){if(r[0].service_hours){try{svcHours=JSON.parse(r[0].service_hours)}catch(e){}}if(r[0].announcement){try{svcAnnouncement=JSON.parse(r[0].announcement)}catch(e){}}if(r[0].service_info)svcInfoText=r[0].service_info}renderAnnouncement();renderHours();renderInfoText()}
async function upsertSettings(data){try{var res=await api('PATCH','settings','?id=eq.1',data);if(!res||!res.length){data.id=1;await api('POST','settings','',data)}}catch(e){try{data.id=1;await api('POST','settings','',data)}catch(e2){}}}
function renderAnnouncement(){var s=document.getElementById('sa-status'),m=document.getElementById('sa-msg'),ab=document.getElementById('sa-activate-btn'),db2=document.getElementById('sa-deactivate-btn');if(!s)return;if(svcAnnouncement.enabled){s.textContent='ACTIVE';s.style.background='var(--rdl)';s.style.color='var(--rd)';if(ab)ab.style.display='none';if(db2)db2.style.display='block'}else{s.textContent='OFF';s.style.background='var(--bg4)';s.style.color='var(--tx3)';if(ab)ab.style.display='block';if(db2)db2.style.display='none'}if(m)m.value=svcAnnouncement.message||''}
async function activateAnnouncement(){var m=document.getElementById('sa-msg');var t=m?m.value.trim():'';if(!t){alert('Enter a message first');return}svcAnnouncement={enabled:true,message:t};await upsertSettings({announcement:JSON.stringify(svcAnnouncement)});await logAct('activate_announcement','settings');renderAnnouncement();alert('Announcement ACTIVE')}
async function deactivateAnnouncement(){svcAnnouncement.enabled=false;await upsertSettings({announcement:JSON.stringify(svcAnnouncement)});await logAct('deactivate_announcement','settings');renderAnnouncement();alert('Announcement deactivated')}
function timeOpts(sel){var h='';for(var hr=0;hr<24;hr++){for(var mn=0;mn<60;mn+=30){var v=(hr<10?'0':'')+hr+':'+(mn<10?'0':'')+mn;var ap=hr>=12?'PM':'AM';var dh=hr%12||12;var label=dh+':'+(mn<10?'0':'')+mn+' '+ap;h+='<option value="'+v+'"'+(v===sel?' selected':'')+'>'+label+'</option>'}}return h}
function renderHours(){var el=document.getElementById('svc-hours');if(!el)return;el.innerHTML=DAYS.map(function(day){var h=svcHours[day]||{open:'12:00',close:'21:00',enabled:true};var r='<div style="display:flex;align-items:center;gap:8px;padding:10px 0;border-bottom:1px solid var(--bdr)">';r+='<label style="min-width:24px"><input type="checkbox" id="sh-cb-'+day+'" '+(h.enabled?'checked':'')+' style="accent-color:var(--bl);width:18px;height:18px"></label>';r+='<span style="font-size:13px;font-weight:700;width:46px">'+day.slice(0,3)+'</span>';r+='<select id="sh-o-'+day+'" style="flex:1;padding:8px 4px;background:var(--bg3);border:1px solid var(--bdr);border-radius:var(--r);color:var(--tx);font-size:12px;font-family:var(--mono);outline:none">'+timeOpts(h.open||'12:00')+'</select>';r+='<span style="color:var(--tx3);font-size:11px">to</span>';r+='<select id="sh-c-'+day+'" style="flex:1;padding:8px 4px;background:var(--bg3);border:1px solid var(--bdr);border-radius:var(--r);color:var(--tx);font-size:12px;font-family:var(--mono);outline:none">'+timeOpts(h.close||'21:00')+'</select>';r+='</div>';return r}).join('')}
async function saveHours(){DAYS.forEach(function(day){var cb=document.getElementById('sh-cb-'+day);var op=document.getElementById('sh-o-'+day);var cl=document.getElementById('sh-c-'+day);svcHours[day]={open:op?op.value:'12:00',close:cl?cl.value:'21:00',enabled:cb?cb.checked:true}});await upsertSettings({service_hours:JSON.stringify(svcHours)});await logAct('update_hours','settings');alert('Hours saved!')}
function renderInfoText(){var inp=document.getElementById('svc-info-text');if(inp)inp.value=svcInfoText}
async function saveInfoText(){var inp=document.getElementById('svc-info-text');svcInfoText=inp?inp.value.trim():'';await upsertSettings({service_info:svcInfoText});await logAct('update_info','settings');alert('Info text saved!')}
