// RYDZ Rider - Category Search

document.addEventListener('click',function(e){if(!e.target.closest('.fw')){closeAC()}});

function catGrid(k){var SVG_RECENT='<svg width="16" height="16" fill="none" stroke="#fff" stroke-width="2"><circle cx="8" cy="8" r="6.5"/><path d="M8 4.5v3.5l2 1.5"/></svg>';var SVG_HOME='<svg width="16" height="16" fill="none" stroke="#fff" stroke-width="2"><path d="M2 7l6-5 6 5v6a1 1 0 01-1 1H3a1 1 0 01-1-1V7z"/><path d="M6 14v-5h4v5"/></svg>';var SVG_DINING='<svg width="16" height="16" fill="none" stroke="#fff" stroke-width="2"><path d="M3 1v5a2 2 0 004 0V1M5 8v6M11 1v2a2 2 0 002 2 2 2 0 002-2V1M13 5v9"/></svg>';var SVG_HOTELS='<svg width="16" height="16" fill="none" stroke="#fff" stroke-width="2"><rect x="1" y="6" width="14" height="8" rx="1"/><path d="M4 6V4a2 2 0 012-2h4a2 2 0 012 2v2"/><circle cx="6" cy="10" r="1"/><path d="M9 8h4v4H9z"/></svg>';var SVG_SHOPPING='<svg width="16" height="16" fill="none" stroke="#fff" stroke-width="2"><rect x="1" y="5" width="14" height="10" rx="1"/><path d="M1 5l2-3h10l2 3"/><path d="M8 8v3"/></svg>';var SVG_BEACHES='<svg width="16" height="16" fill="none" stroke="#fff" stroke-width="2"><path d="M8 1c-2 3-5 5-7 5.5h14C13 6 10 4 8 1z"/><path d="M8 1v14"/><path d="M1 15h14"/></svg>';return'<div class="ac-grid"><div class="ac-btn" onmousedown="showCat(\''+k+'\',\'recent\')">'+SVG_RECENT+'<span>Recent</span></div><div class="ac-btn" onmousedown="showCat(\''+k+'\',\'home\')">'+SVG_HOME+'<span>Home</span></div><div class="ac-btn" onmousedown="showCat(\''+k+'\',\'dining\')">'+SVG_DINING+'<span>Dining</span></div><div class="ac-btn" onmousedown="showCat(\''+k+'\',\'hotels\')">'+SVG_HOTELS+'<span>Hotels</span></div><div class="ac-btn" onmousedown="showCat(\''+k+'\',\'shopping\')">'+SVG_SHOPPING+'<span>Shopping</span></div><div class="ac-btn" onmousedown="showCat(\''+k+'\',\'beaches\')">'+SVG_BEACHES+'<span>Beaches</span></div></div>'}
function showCat(k,cat){var drop=document.getElementById('ac-'+k);var names=CATS[cat]||[];if(!names.length){drop.innerHTML='<div style="padding:14px;text-align:center;color:var(--g400);font-size:13px">No locations saved yet</div>';drop.classList.add('show');return}var res=P.filter(function(p){return names.indexOf(p.n)>=0});var h='<div class="ac-cat">'+cat.charAt(0).toUpperCase()+cat.slice(1)+'</div>';res.forEach(function(r){h+=acI(k,r)});drop.innerHTML=h;drop.classList.add('show')}
function closeAC(){document.querySelectorAll('.acl').forEach(function(d){d.classList.remove('show')});document.querySelectorAll('.fw').forEach(function(f){f.classList.remove('active')})}
function _origOnTyp(k){closeAC();var inp=document.getElementById(k==='pu'?'f-pu':'f-do'),fd=document.getElementById(k==='pu'?'pu-fd':'do-fd'),drop=document.getElementById('ac-'+k);var fw=drop.parentElement;fw.classList.add('active');var v=inp.value.trim().toLowerCase();fd.classList.toggle('hv',inp.value.length>0);fd.classList.remove('valid');if(k==='pu')puSel=null;else doSel=null;chkBtn();if(v.length<1){drop.innerHTML=catGrid(k);drop.classList.add('show');return}var res=P.filter(function(p){return p.n.toLowerCase().indexOf(v)>=0||p.a.toLowerCase().indexOf(v)>=0}).slice(0,8);if(!res.length){drop.innerHTML='<div style="padding:14px;text-align:center;color:var(--g400);font-size:13px">No results found</div>';drop.classList.add('show');return}var food=res.filter(function(r){return r.t==='food'}),places=res.filter(function(r){return r.t==='place'}),addrs=res.filter(function(r){return r.t==='addr'});var h='';if(food.length){h+='<div class="ac-cat">Restaurants</div>';food.forEach(function(r){h+=acI(k,r)})}if(places.length){h+='<div class="ac-cat">Places</div>';places.forEach(function(r){h+=acI(k,r)})}if(addrs.length){h+='<div class="ac-cat">Addresses</div>';addrs.forEach(function(r){h+=acI(k,r)})}drop.innerHTML=h;drop.classList.add('show')}
function acI(k,r){var idx=P.indexOf(r);var ic=r.t==='food'?'food':r.t==='place'?'place':'addr';var svg=r.t==='food'?ICO_FORK:r.t==='place'?ICO_STAR:ICO_PIN;return'<div class="aci" onmousedown="sel(\''+k+'\','+idx+')"><div class="aic '+ic+'">'+svg+'</div><div class="tx"><div class="mn">'+esc(r.n)+'</div><div class="sb2">'+esc(r.a)+'</div></div></div>'}
function _origSel(k,idx){var p=P[idx],inp=document.getElementById(k==='pu'?'f-pu':'f-do'),fd=document.getElementById(k==='pu'?'pu-fd':'do-fd');inp.value=p.n;fd.classList.add('hv','valid');closeAC();if(k==='pu')puSel=p;else doSel=p;chkBtn();drawMap(document.getElementById('home-map'),{pu:puSel,d:doSel})}
function _origClr(k){var inp=document.getElementById(k==='pu'?'f-pu':'f-do'),fd=document.getElementById(k==='pu'?'pu-fd':'do-fd');inp.value='';fd.classList.remove('hv','valid');document.getElementById('ac-'+k).classList.remove('show');if(k==='pu')puSel=null;else doSel=null;chkBtn();drawMap(document.getElementById('home-map'),{pu:puSel,d:doSel});inp.focus()}
function _origChkBtn(){var b=document.getElementById('h-btn'),ok=puSel&&doSel&&db&&db.settings.serviceStatus;b.disabled=!ok;b.textContent=ok?'Continue':(!puSel&&!doSel?'Select pickup & drop-off to continue':!puSel?'Select a pickup location':'Select a drop-off location')}
