// RYDZ Rider - Promotions

var astimer=null,touching=false;

function renPromos(){var promos=db.settings.promotions||PROMOS;var h=mTop('Promotions');promos.forEach(function(p,i){var img=p.img||PIMG[i%PIMG.length];h+='<div class="pli" onclick="openPD('+i+')"><div class="pli-img" style="background:'+p.color+'"><img src="'+img+'" onerror="this.style.display=\'none\'"></div><div class="pli-text"><h4>'+esc(p.name)+'</h4><p>'+esc(p.addr)+'</p></div></div>'});document.getElementById('ms-promos').innerHTML=h}
function openPD(idx){closeAllM();var promos=db.settings.promotions||PROMOS;var p=promos[idx];if(!p)return;var img=p.img||PIMG[idx%PIMG.length];document.getElementById('ms-promo-detail').innerHTML='<div class="mtop"><button class="btn btn-ghost" onclick="openM(\'promos\')"><svg width="20" height="20" fill="none" stroke="var(--g800)" stroke-width="2" stroke-linecap="round"><path d="M17 10H3M10 17l-7-7 7-7"/></svg></button><h2>Promotion</h2></div><div class="pd"><div class="pd-img" style="background:'+p.color+'"><img src="'+img+'" onerror="this.style.display=\'none\'"></div><h3>'+esc(p.name)+'</h3><p class="pd-a">'+esc(p.addr)+'</p><p class="pd-d">'+esc(p.desc)+'</p></div>';document.getElementById('ms-promo-detail').classList.add('on')}
function openPDHome(idx){openM('promos');setTimeout(function(){openPD(idx)},100)}
function renPromoScroll(){var el=document.getElementById('promo-trk');if(!el)return;var promos=db.settings.promotions||PROMOS;var all=promos.concat(promos);el.innerHTML=all.map(function(p,i){var img=p.img||PIMG[i%PIMG.length];return'<div class="promo-cd" onclick="openPDHome('+(i%promos.length)+')"><img src="'+img+'" onerror="this.style.display=\'none\';this.parentElement.style.background=\''+p.color+'\'"><div class="promo-ol">'+esc(p.name)+'</div></div>'}).join('');startAutoScroll()}
function startAutoScroll(){if(astimer)clearInterval(astimer);var w=document.querySelector('.promo-track-wrap');if(!w)return;w.ontouchstart=function(){touching=true};w.ontouchend=function(){touching=false};w.onmouseenter=function(){touching=true};w.onmouseleave=function(){touching=false};astimer=setInterval(function(){if(touching)return;w.scrollLeft+=1;if(w.scrollLeft>=w.scrollWidth/2)w.scrollLeft=0},30)}
