// RYDZ Admin - Helpers

function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}
function ago(d){var s=Math.floor((Date.now()-d.getTime())/1000);if(s<60)return'Just now';if(s<3600)return Math.floor(s/60)+'m ago';if(s<86400)return Math.floor(s/3600)+'h ago';return Math.floor(s/86400)+'d ago'}
function getDayStart(){var d=new Date();if(d.getHours()<5)d.setDate(d.getDate()-1);d.setHours(5,0,0,0);return d.getTime()}
function exportCSV(type){var rows=[];if(type==='riders'){rows.push(['Name','Email','Phone','Rides','Completed','Cancelled','Status']);users.filter(function(u){return u.role!=='driver'&&u.role!=='admin'}).forEach(function(u){var ur=rides.filter(function(r){return r.rider_id===u.id});var c=ur.filter(function(r){return r.status==='completed'}).length;var x=ur.filter(function(r){return r.status==='cancelled'}).length;rows.push([u.name,u.email,u.phone,ur.length,c,x,u.disabled?'Disabled':'Active'])})}else{rows.push(['Name','Email','Phone','Vehicle','Plate','Username','Rides','Rating','Status']);users.filter(function(u){return u.role==='driver'}).forEach(function(d){var dr=rides.filter(function(r){return r.driver_id===d.id});var c=dr.filter(function(r){return r.status==='completed'}).length;var rated=dr.filter(function(r){return r.rating});var avg=rated.length?(rated.reduce(function(a,r){return a+r.rating},0)/rated.length).toFixed(1):'--';rows.push([d.name,d.email,d.phone,d.vehicle,d.plate,d.username,c,avg,d.disabled?'Disabled':'Active'])})}
var csv=rows.map(function(r){return r.map(function(c){return'"'+String(c||'').replace(/"/g,'""')+'"'}).join(',')}).join('\n');var b=new Blob([csv],{type:'text/csv'});var a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='rydz-'+type+'-'+new Date().toISOString().slice(0,10)+'.csv';a.click()}
function sect(t,c){return'<div class="pn-sect"><h4>'+t+'</h4>'+c+'</div>'}
function row(l,v){return'<div class="pn-row"><span class="lb">'+l+'</span><span class="vl">'+(v||'--')+'</span></div>'}
function startClock(){function tick(){var now=new Date();var days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];var months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];var dateStr=days[now.getDay()]+', '+months[now.getMonth()]+' '+now.getDate();var h=now.getHours(),ampm=h>=12?'PM':'AM';h=h%12||12;var m=String(now.getMinutes()).padStart(2,'0');var s=String(now.getSeconds()).padStart(2,'0');var el=document.getElementById('hdr-date');if(el)el.textContent=dateStr;var el2=document.getElementById('hdr-time');if(el2)el2.textContent=h+':'+m+':'+s+' '+ampm}tick();setInterval(tick,1000)}
function noteBlock(uid,notes){return'<div style="max-height:160px;overflow-y:auto">'+(notes&&notes.length?notes.map(function(n){return'<div class="note-item">'+esc(n.note)+'<div class="note-meta">'+esc(n.admin_name)+' &middot; '+ago(new Date(n.created_at))+'</div></div>'}).join(''):'<div style="color:var(--tx3);font-size:12px">No notes</div>')+'</div><textarea class="note-inp" id="nt-inp" rows="2" placeholder="Add note..."></textarea><button class="btn btn-p" style="width:100%" data-xid="'+uid+'" onclick="addNote(this.dataset.xid)">Add Note</button>'}
