// RYDZ Admin - Panels

function openPN(){document.getElementById('pn-ov').classList.add('on');document.getElementById('pn').classList.add('on')}
function closePN(){document.getElementById('pn-ov').classList.remove('on');document.getElementById('pn').classList.remove('on')}
async function togDis(uid,v){await api('PATCH','users','?id=eq.'+encodeURIComponent(uid),{disabled:v});await logAct(v?'disable':'enable',uid);await loadData();closePN()}
async function addNote(uid){var inp=document.getElementById('nt-inp');var t=inp?inp.value.trim():'';if(!t)return;await api('POST','admin_notes','',{user_id:uid,note:t,admin_role:admin.role,admin_name:admin.name});inp.value='';var u=users.find(function(x){return x.id===uid});if(u&&u.role==='driver')openDrvPN(uid);else openRdrPN(uid)}
async function logAct(a,tid){await api('POST','admin_logs','',{action:a,target_id:tid,admin_role:admin.role,admin_name:admin.name})}
function openRidePN(rid){var r=rides.find(function(x){return x.id===rid});if(!r)return;var rider=users.find(function(u){return u.id===r.rider_id});var driver=r.driver_id?users.find(function(u){return u.id===r.driver_id}):null;var sc=r.status==='completed'?'var(--gn)':r.status==='cancelled'?'var(--rd)':r.status==='requested'?'var(--or)':'var(--bl)';
document.getElementById('pn-title').textContent='Ride Details';
var isDispatch=!r.rider_id&&r.note;var dispName=r.note||'';if(dispName.indexOf('DISPATCH:')===0)dispName=dispName.replace('DISPATCH: ','').split(' | ')[0];var phoneIcon=' <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--bl)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align:middle;margin-left:4px"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72 12.84 12.84 0 00.7 2.81 2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45 12.84 12.84 0 002.81.7A2 2 0 0122 16.92z"/></svg>';var riderSect;if(rider){riderSect=sect('Rider',row('Name',rider.name)+row('Email',rider.email)+row('Phone',rider.phone))}else if(isDispatch){riderSect=sect('Caller',row('Name',esc(dispName)+phoneIcon)+(r.phone?row('Phone',r.phone):''))}else{riderSect=sect('Rider','<span style="color:var(--tx3)">Unknown</span>')}
document.getElementById('pn-body').innerHTML=sect('Ride Info',row('Status','<span class="badge" style="background:'+sc+'22;color:'+sc+'">'+r.status+'</span>')+row('Pickup',r.pickup)+row('Drop-off',r.dropoff)+row('Passengers',r.passengers||1))+riderSect+(driver?sect('Driver',row('Name',driver.name)+row('Vehicle',driver.vehicle)):'');
document.getElementById('pn-acts').innerHTML='';openPN()}
