// RYDZ Driver - Authentication
// Login, logout, vehicle selection, onboarding

async function doLogin(){var u=document.getElementById('dl-user').value.trim(),p=document.getElementById('dl-pass').value;var err=document.getElementById('dl-err');if(!u||!p){err.textContent='Enter username and password.';err.classList.add('show');return}
err.classList.remove('show');
try{var res=await supaFetch('GET','users','?username=eq.'+encodeURIComponent(u)+'&password=eq.'+encodeURIComponent(p)+'&role=eq.driver');
if(res&&res.length){var user=res[0];
if(user.disabled){err.textContent='Your account has been disabled. Please contact your administrator to enable it.';err.classList.add('show');return}
selUser=user;DID=user.id;localStorage.setItem('rydz-drv-id',user.id);localStorage.setItem('rydz-drv-name',user.name);localStorage.setItem('rydz-drv-login-ts',String(Date.now()));if(typeof _scheduleNext5amLogout==='function')_scheduleNext5amLogout();if(typeof subscribeDriverRealtime==='function')subscribeDriverRealtime();supaSync();go('vehicle');return}}catch(e){}
if(u==='test'&&p==='1'){DID='d1';localStorage.setItem('rydz-drv-id','d1');localStorage.setItem('rydz-drv-login-ts',String(Date.now()));if(typeof _scheduleNext5amLogout==='function')_scheduleNext5amLogout();if(typeof subscribeDriverRealtime==='function')subscribeDriverRealtime();go('vehicle');return}
err.textContent='Invalid username or password.';err.classList.add('show')}
function doLogout(){closeSB();stopGPS();localStorage.setItem('rydz-drv-online','false');var _d=gD();if(_d){_d.status='offline';sv();supaFetch('PATCH','users','?id=eq.'+encodeURIComponent(DID),{status:'offline',lat:null,lng:null})}if(typeof unsubscribeDriverRealtime==='function')unsubscribeDriverRealtime();DID=null;localStorage.removeItem('rydz-drv-id');localStorage.removeItem('rydz-drv-name');localStorage.removeItem('rydz-drv-login-ts');if(typeof _logoutTimer!=='undefined'&&_logoutTimer){try{clearTimeout(_logoutTimer)}catch(e){}_logoutTimer=null}go('login')}
function renVeh(){var g=document.getElementById('veh-grid');if(!g)return;g.innerHTML=VEHS.map(function(v){return'<div class="veh-opt'+(selVeh===v.id?' sel':'')+'" onclick="pickV(\''+v.id+'\')"><svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="1" y="8" width="22" height="8" rx="2"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/><path d="M8 16h8"/><path d="M3 8l2-4h14l2 4"/><path d="M8 8V4M16 8V4"/><line x1="1" y1="12" x2="23" y2="12"/></svg><div class="vn">'+esc(v.name)+'</div><div class="vd">'+esc(v.desc)+'</div></div>'}).join('')}
function pickV(id){selVeh=id;renVeh();document.getElementById('veh-btn').disabled=false}
function goMain(){if(!selVeh)return;var v=VEHS.find(function(x){return x.id===selVeh});var drv=gD();if(drv&&v){drv.vehicle=v.desc;drv.status='offline';localStorage.setItem('rydz-drv-online','false');sv();supaUpdateUser(drv);document.getElementById('h-nm').textContent=drv.name;document.getElementById('h-av').textContent=(drv.name||'D')[0];document.getElementById('h-vc').textContent=v.desc||''}supaSync();setTimeout(function(){ren()},2000);go('main')}
