// RYDZ Driver - Dashboard UI
// Main dashboard render function

function ren(){var drv=gD();if(!drv){drv={name:localStorage.getItem('rydz-drv-name')||'Driver',vehicle:'',status:'offline'}};document.getElementById('h-av').textContent=drv.name[0];document.getElementById('h-nm').textContent=drv.name;document.getElementById('h-vc').textContent=drv.vehicle||'';var on=localStorage.getItem('rydz-drv-online')==='true',mr=gMR(),inc=gIn(),c=document.getElementById('cnt');var h='';
var htg=document.getElementById('h-tg');if(htg){htg.className='tg '+(on?'on':'off')}
if(mr){var ri=db.users.find(function(u){return u.id===mr.riderId});var riderName=ri?ri.name:'Dispatch Ride';var riderPhone=mr.phone||(ri?ri.phone:'')||'';var sl={accepted:'ACCEPTED',arrived:'AT PICKUP',picked_up:'IN TRANSIT'}[mr.status]||'';var bc=mr.status==='arrived'?'bg2':mr.status==='picked_up'?'bo':'bb';h+='<div class="card act"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px"><div><div class="bdg '+bc+'">'+sl+'</div><h4 style="font-size:16px;font-weight:800;margin-top:8px">Active Ride</h4></div><div style="text-align:right"><span style="font-size:10px;color:var(--g400);font-family:var(--font2)">Rider</span><p style="font-weight:700;font-size:13px;margin-top:1px">'+esc(riderName)+'</p></div></div>';h+='<div class="route">'+RDOTS+'<div class="route-i"><span class="route-lbl">PICKUP</span><p>'+esc(mr.pickup)+'</p><div class="route-dv"><span class="route-lbl">DROP-OFF</span><p>'+esc(mr.dropoff)+'</p></div></div></div><div class="stats"><div class="stat"><span class="l">Pass.</span><span class="v">'+mr.passengers+'</span></div></div>'+
'<a onclick="openDirections()" style="display:flex;align-items:center;justify-content:center;gap:8px;padding:12px;background:linear-gradient(135deg,#007AFF,#3898ff);border-radius:12px;color:#fff;font-weight:700;font-size:14px;font-family:var(--font);cursor:pointer;margin:10px 0;text-decoration:none;box-shadow:0 3px 12px rgba(0,122,255,.25)"><svg width="18" height="18" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round"><path d="M12 2C8 2 5 5 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5a2.5 2.5 0 110-5 2.5 2.5 0 010 5z"/></svg>Open Directions</a>'+
'';h+='<div style="font-size:12px;color:var(--g500);margin-bottom:8px;padding:0 2px;font-family:var(--font2)"><b style="color:var(--g400)">Notes:</b> '+esc(mr.note||'None')+'</div>';if(riderPhone)h+='<a href="tel:'+esc(riderPhone)+'" style="display:flex;align-items:center;justify-content:center;gap:7px;padding:11px;background:var(--gnl);border:1px solid rgba(52,199,89,.15);border-radius:var(--r);text-decoration:none;color:var(--gn);font-weight:700;font-size:13px;font-family:var(--font);margin-bottom:10px"><svg width="14" height="14" fill="none" stroke="var(--gn)" stroke-width="2"><path d="M1 2.5A1.5 1.5 0 012.5 1h2.1a1 1 0 01.95.68l.7 2.1a1 1 0 01-.26 1.03l-.9.9a8 8 0 003.2 3.2l.9-.9a1 1 0 011.03-.26l2.1.7a1 1 0 01.68.95v2.1a1.5 1.5 0 01-1.5 1.5A12 12 0 011 2.5z"/></svg>Call Rider</a>';if(mr.status==='accepted')h+='<button class="btn btn-p btn-w" style="padding:13px;font-size:14px" onclick="upSt(\'arrived\')">Arrived at Pickup</button>';if(mr.status==='arrived')h+='<button class="btn btn-p btn-w" style="padding:13px;font-size:14px;background:var(--cy)" onclick="upSt(\'picked_up\')">Picked Up Rider</button>';if(mr.status==='picked_up')h+='<button class="btn btn-s btn-w" style="padding:13px;font-size:14px;background:#ff9f0a" onclick="upSt(\'completed\')">Drop Off - Complete Ride</button>';h+='</div>'}
if(on&&inc.length>0){h+='<h4 style="font-size:14px;font-weight:800;margin:4px 0 10px">Incoming Requests</h4>';var oldestId=inc[0]?inc[0].id:null;inc.forEach(function(r,rIdx){var ri=r.riderId?db.users.find(function(u){return u.id===r.riderId}):null;var riderName=ri?ri.name:'Dispatch Ride';var riderPhone=r.phone||(ri?ri.phone:'')||'';var isFirst=r.id===oldestId&&!mr;var qNum=rIdx+1;var cardStyle=isFirst?'':'opacity:.55;pointer-events:none';h+='<div class="card req" style="'+cardStyle+'"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px"><div class="bdg '+(isFirst?'bb':'bg3')+'">'+(isFirst?'NEXT UP':'#'+(rIdx+1)+' IN QUEUE')+'</div><span style="font-size:11px;color:var(--g400)">'+fmt(r.createdAt)+'</span></div><div class="route">'+RDOTS+'<div class="route-i"><span class="route-lbl">PICKUP</span><p>'+esc(r.pickup)+'</p><div class="route-dv"><span class="route-lbl">DROP-OFF</span><p>'+esc(r.dropoff)+'</p></div></div></div><div style="display:flex;align-items:center;justify-content:space-between;margin-top:8px;padding:10px 12px;background:var(--g50);border:1px solid var(--g150);border-radius:10px"><div><span style="font-size:10px;color:var(--g400);text-transform:uppercase;letter-spacing:.3px">Rider</span><p style="font-weight:700;font-size:13px;margin-top:1px">'+esc(riderName)+'</p></div><div style="display:flex;align-items:center;gap:8px"><span style="font-size:12px;color:var(--g500)">'+r.passengers+' pass.</span>'+(riderPhone&&isFirst?'<a href="tel:'+esc(riderPhone)+'" style="display:flex;align-items:center;gap:5px;padding:8px 14px;background:var(--gn);color:#fff;border-radius:10px;text-decoration:none;font-weight:700;font-size:12px"><svg width="14" height="14" fill="none" stroke="#fff" stroke-width="2"><path d="M1 2.5A1.5 1.5 0 012.5 1h2.1a1 1 0 01.95.68l.7 2.1a1 1 0 01-.26 1.03l-.9.9a8 8 0 003.2 3.2l.9-.9a1 1 0 011.03-.26l2.1.7a1 1 0 01.68.95v2.1a1.5 1.5 0 01-1.5 1.5A12 12 0 011 2.5z"/></svg>Call</a>':'')+'</div></div>';if(isFirst){h+='<div style="display:flex;gap:8px;margin-top:10px"><button class="btn btn-o" style="flex:1;padding:13px 20px;font-size:14px" onclick="decRide(\''+r.id+'\')">Decline</button><button class="btn btn-s" style="flex:1;padding:13px 20px;font-size:14px" onclick="acc(\''+r.id+'\')">Accept</button></div>'}else{h+='<div style="padding:10px;background:var(--g100);border-radius:10px;text-align:center;font-size:12px;color:var(--g400)">Waiting in queue</div>'}h+='</div>'})}
if(on&&!inc.length&&!mr)h+='<div class="card"><div class="empty"><svg width="40" height="40" fill="none" stroke="var(--g300)" stroke-width="1.5"><circle cx="20" cy="20" r="16"/><path d="M14 20h12M20 14v12"/></svg><h4>Waiting for rides</h4><p>New requests will appear here automatically.</p></div></div>';
if(!on&&!mr)h+='<div class="card"><div class="empty"><svg width="40" height="40" fill="none" stroke="var(--g300)" stroke-width="1.5"><circle cx="20" cy="20" r="16"/><path d="M16 16l8 8M24 16l-8 8"/></svg><h4>You are offline</h4><p>Go online to start receiving rides.</p></div></div>';
if(!db.settings.serviceStatus)h+='<div class="svc-alert"><svg width="13" height="13" fill="none" stroke="var(--rd)" stroke-width="2"><circle cx="6.5" cy="6.5" r="5.5"/><path d="M6.5 8.5V6.5M6.5 4.5h.01"/></svg>Service shut down by admin</div>';
c.innerHTML=h;}
